import React, { Component } from "react";

export default class Privacy extends Component {
    render(){
        return(
            <div className="row">
                <div className="margin-body">
                    <header className="entry-title">
                        <h2>Privacy Policy</h2>
                    </header>
                    <div className="post-content">
                        <p><span>Selamat datang di Aplikasi JastipinAja! yang dioperasikan oleh PT. Anjana Nata Alam. JastipinAja! dengan serius bertanggung jawab berdasarkan peraturan perundang-undangan tentang privasi yang berlaku dan berkomitmen untuk menghormati hak dan masalah semua pengguna Aplikasi JastipinAja!. Kami mengakui pentingnya data pribadi yang telah Anda percayakan kepada kami dan percaya bahwa merupakan tanggung jawab kami untuk mengelola, melindungi dan mengolah data pribadi anda dengan baik. Kebijakan Privasi ini dirancang untuk membantu anda memahami bagaimana kami mengumpulkan , menggunakan, mengungkapkan dan/atau mengolah data pribadi yang telah Anda percayakan kepada kami dan/atau kami miliki tentang anda, baik di masa sekarang maupun di masa mendatang, serta untuk membantu anda membuat keputusan yang tepat sebelum memberikan data pribadi anda kepada kami.</span></p>
                        <p><span><strong>A&nbsp;&nbsp;Pendahuluan</strong></span></p>
                        <ul>
                            <li><span>Data Pribadi adalah data, baik benar maupun tidak, tentang individu yang dapat diidentifikasi dari data tersebut, atau dari data dan informasi lainnya yang dapat atau kemungkinan dapat diakses oleh suatu organisasi. Contoh umum data pribadi dapat mencakup nama, nomor identitas dan informasi kontak.</span></li>
                            <li><span>Dengan menggunakan aplikasi, mendaftarkan akun pada kami, mengunjungi aplikasi kami, Anda mengakui dan setuju bahwa anda menerima praktik, persyaratan, dan/atau kebijakan yang diuraikan dalam Kebijakan Privasi ini, dan Anda dengan ini mengizinkan kami untuk mengumpulkan, menggunakan, mengungkapkan dan/atau mengolah data pribadi anda seperti yang dijelaskan disini. Apabila anda tidak mengizinkan pengolahan data pribadi anda seperti yang dijelaskan dalam Kebijakan Privasi ini, mohon jangan mengunakan atau mengakses aplikasi kami.</span></li>
                            <li><span>Apabila kami mengubah Kebijakan Privasi kami, kami akan memposting perubahan tersebut atau Kebijakan Privasi yang telah diubah pada Aplikasi kami. Kami berhak mengubah Kebijakan Privasi ini setiap saat.</span></li>
                        </ul>
                        <hr />
                        <p><span><strong>B.&nbsp;&nbsp;Pengumpulan Data Pribadi</strong></span></p>
                        <p><span>1. Kami akan/mungkin mengumpulkan data pribadi Anda :</span></p>
                        <ul>
                            <li><span>Saat anda mendaftar dan/atau menggunakan aplikasi kami atau membuka sebuah akun dengan kami.</span></li>
                            <li><span>Saat anda berinteraksi dengan kami, seperti melalui email, media sosial, surat, dan pertemuan tatap muka.</span></li>
                            <li><span>Saat anda melakukan transaksi melalui aplikasi kami.</span></li>
                            <li><span>Saat anda menyampaikan kritik dan saran atau keluhan kepada kami.</span></li>
                            <li><span>Saat anda mengirimkan data pribadi anda kepada kami dengan alasan apapun. Daftar diatas tidak dimaksudkan sebagai suatu daftar yang lengkap dan hanya menetapkan beberapa contoh umum tentang kapan data pribadi anda mungkin diambil.</span></li>
                        </ul>
                        <p><span>2. Data pribadi yang mungkin dikumpulkan oleh JastipinAja! termasuk namun tidak terbatas pada :</span></p>
                        <ul>
                            <li><span>Nama</span></li>
                            <li><span>Alamat email</span></li>
                            <li><span>Nomor telepon</span></li>
                            <li><span>Alamat rumah</span></li>
                            <li><span>Rekening bank dan informasi pembayaran</span></li>
                            <li>Informasi yang dikirim oleh atau terhubung dengan perangkat (-perangkat) yang digunakan untuk mengakses aplikasi</li>
                            <li>Informasi lain apapun tentang pengguna saat pengguna mendaftarkan diri untuk menggunakan aplikasi kami, dan saat pengguna menggunakan aplikasi, serta informasi yang berkaitan dengan bagaimana pengguna menggunakan aplikasi kami ; dan</li>
                            <li>Seluruh data tentang konten yang digunakan pengguna</li>
                        </ul>
                        <hr />
                        <p><span><strong>C.&nbsp;&nbsp;Pengumpulan Data Lainnya</strong></span></p>
                        <ul>
                            <li><span>Seperti kebanyakan aplikasi mobile, perangkat anda mengirimkan informasi yang mungkin, mencakup data mengenai anda yang dapat dicatat oleh server web apabila anda menggunakan aplikasi kami. Ini biasanya termasuk tanpa terbatas, alamat Internet Protocol (IP) perangkat anda, sistem operasi komputer/perangkat mobile, karakteristik perangkat mobile, Unique Device Identifier (UDID), Mobile Equipment Identifier (MEID) untuk perangkat mobile anda, alamat dari situs yang merekomendasikan (apabila ada), halaman yang anda kunjungi di aplikasi mobile dan waktu kunjungan anda, dan kadang “cookie” (yang dapat dinonaktifkan dengan menggunakan preferensi browser anda) untuk membantu situs mengingat kunjungan anda yang terakhir. Jika Anda log in (masuk), informasi ini dikaitkan dengan akun pribadi anda. Informasi tersebut juga disertakan dalam statistik anonim untuk memungkinkan kami memahami cara pengunjung menggunakan aplikasi kami.</span></li>
                            <li><span>Aplikasi mobile kami dapat mengumpulkan informasi rinci tentang lokasi dari perangkat mobile dengan menggunakan teknologi seperti GPS, Wi-Fi, dan lain lain. Kami mengumpulkan, menggunakan, membuka dan/atau memproses informasi untuk satu tujuan atau lebih, tidak terbatas, layanan berbasis lokasi yang anda minta atau untuk mengirimkan konten kepada anda berdasarkan lokasi anda atau untuk mengijinkan anda membagikan lokasi ke pengguna lainnya sebagai bagian dari layanan pada aplikasi mobile kami. Untuk sebagian besar perangkat mobile, Anda dapat mencabut persetujuan yang Anda berikan kepada kami untuk memperoleh informasi ini pada lokasi anda melalui pengaturan perangkat anda. Jika ada pertanyaan mengenai cara menonaktifkan layanan lokasi perangkat mobile anda, silakan menghubungi penyedia layanan perangkat mobile anda atau produsen perangkatnya.</span></li>
                        </ul>
                        <hr />
                        <p><span><strong>D.&nbsp;&nbsp;Cookie</strong></span></p>
                        <ul>
                            <li><span>Sewaktu-waktu, kami dapat mengimplementasikan “cookie” atau fitur lain untuk memungkinkan kami mengumpulkan atau berbagai informasi yang akan membantu kami memperbaiki aplikasi yang kami tawarkan, atau membantu kami menawarkan layanan serta fitur baru. “Cookie” adalah pengenal yang akan kami alihkan ke komputer atau perangkat mobile Anda yang memungkinkan kami mengenali komputer atau perangkat anda dan memberi tahu kami mengenai bagaimana dan kapan aplikasi digunakan atau dikunjungi, oleh berapa banyak orang, dan untuk melacak aktifitas di dalam aplikasi kami. Kami dapat menautkan informasi cookie ke data pribadi. Cookie juga tertaut ke informasi mengenai item apa yang sudah anda pilih untuk halaman dan pembelian yang anda lihat. Informasi ini juga digunakan untuk melacak keranjang belanja anda, misalnya cookie juga digunakan untuk menyampaikan konten spesifik sesuai minat anda dan untuk memantau penggunaan aplikasi kami.</span></li>
                            <li><span>Anda boleh menolak penggunaan cookie dengan memilih pengaturan yang sesuai pada browser anda. Bagaimanapun, harap diperhatikan bahwa jika anda melakukan ini, anda tidak dapat menggunakan fungsionalitas penuh aplikasi kami.</span></li>
                        </ul>
                        <hr />
                        <p><span><strong>E.&nbsp;&nbsp;Melihat dan Mengunduh Konten dan Iklan</strong></span></p>
                        <ul>
                            <li><span>Sama seperti ketika menjelajahi halaman pada aplikasi mobile kami, saat anda melihat konten dan iklan serta mengakses perangkat lunak lainnya di aplikasi kami, sebagian dari informasi yang sama dikirimkan kepada kami (termasuk, dengan tidak terbatas pada, Alamat IP, sistem operasi, dan sebagainya); tetapi bukannya tentang berapa kali halaman dilihat, komputer anda mengirimkan informasi kepada kami tentang konten, iklan yang dilihat dan/atau perangkat lunak yang dipasang oleh aplikasi dan waktu.</span></li>
                        </ul>
                        <hr />
                        <p><span><strong>F.&nbsp;&nbsp;Bagaimana Kami Menggunakan Informasi Yang Anda Berikan Kepada Kami ?</strong></span></p>
                        <p><span>1. Kami dapat mengumpulkan, menggunakan, mengungkapkan dan/atau mengolah data pribadi Anda untuk satu atau lebih dari tujuan-tujuan berikut ini :</span></p>
                        <ul>
                            <li><span>Mempertimbangkan dan/atau mengolah aplikasi/transaksi anda dengan kami atau transaksi maupun komunikasi Anda dengan pihak ketiga melalui aplikasi.</span></li>
                            <li><span>Mengelola, mengoperasikan, menyediakan, dan/atau mengurus penggunaan dan/atau akses anda ke aplikasi kami (termasuk, namun tidak terbatas pada, mengingat preferensi anda) serta hubungan anda dan akun pengguna anda dengan kami.</span></li>
                            <li><span>Menanggapi, mengolah, berurusan dengan atau menyelesaikan transaksi dan/atau memenuhi permintaan anda untuk produk tertentu serta memberi tahu anda tentang masalah layanan dan tindakan akun yang tidak lazim.</span></li>
                            <li><span>Memberlakukan persyaratan layanan atau perjanjian lisensi pengguna akhir apapun yang berlaku.</span></li>
                            <li><span>Melindungi keselamatan pribadi dan hak, milik atau keselamatan pihak lainnya.</span></li>
                            <li><span>Untuk identifikasi dan/atau verifikasi.</span></li>
                            <li>Mempertahankan dan memberikan setiap pembaruan perangkat lunak dan/atau pembaruan lainnya serta dukungan yang mungkin diperlukan dari waktu ke waktu untuk memastikan kelancaran layanan kami.</li>
                            <li>Berurusan dengan atau memfasilitasi layanan pelanggan, melaksanakan instruksi anda, berurusan dengan atau menanggapi setiap pertanyaan yang diajukan oleh (konon diajukan oleh) anda atau atas nama anda.</li>
                            <li>Menghubungi anda atau berkomunikasi dengan anda melalui email, surat pos, atau cara lainnya untuk tujuan mengurus dan/atau mengelola hubungan anda dengan kami atau penggunaan layanan kami oleh anda, seperti tetapi tidak terbatas pada mengkomunikasikan informasi administratif kepada anda yang berkaitan dengan layanan kami. Anda mengakui dan setuju bahwa komunikasi semacam itu oleh kami dapat dilakukan dengan mengirim surat, dokumen atau pemberitahuan kepada anda, yang dapat melibatkan pengungkapan data pribadi tertentu tentang anda untuk melakukan pengiriman tersebut serta tercantum juga pada sampul luar amplop/Paket pos.</li>
                            <li>Mengadakan kegiatan penelitian, analisis dan pengembangan (termasuk, tetapi tidak terbatas pada, analisis data, survey, pengembangan produk dan layanan dan/atau pembuatan profil), untuk menganalisis bagaimana anda menggunakan layanan kami, meningkatkan layanan kami dan/atau meningkatkan pengalaman pekanggan anda.</li>
                            <li>Memungkinkan audit dan survey untuk, antara lain, memvalidasi ukuran dan komposisi audiens sasaran kami, serta memahami pengalaman mereka dengan layanan JastipinAja!.</li>
                            <li>Untuk pemasaran, dan dalam hal ini, mengirimi anda melalui berbagai moda komunikasi, informasi pemasaran dan promosi serta materi yang berkaitan dengan produk dan/atau layanan (termasuk, tapi tidak terbatas pada produk dan/atau layanan pihak ketiga yang berkolaborasi atau terkait dengan JastipinAja!) yang mana JastipinAja! dapat menjual, memasarkan atau mempromosikan, baik produk atau layanan tersebut ada sekarang, atau dibuat di waktu mendatang. Anda dapat berhenti berlangganan dari penerimaan informasi pemasaran setiap waktunya dengan menggunakan informasi kontak anda untuk mengirimkan newsletter dari kami dan dari perusahaan yang terkait oleh kami.</li>
                            <li>Menanggapi proses hukum atau mematuhi atau sebagaimana diwajibkan oleh setiap hukum, persyaratan pemerintah atau peraturan yang berlaku dengan yurisdiksi yang relevan, termasuk, dengan tidak terbatas pada, memenuhi persyaratan untuk melakukan pengungkapan berdasarkan persyaratan hukum yang mengikat JastipinAja! atau perusahaan terkait.</li>
                            <li>Menghasilkan statistik dan penelitian untuk pelaporan internal dan yang diwajibkan oleh hukum dan/atau persyaratan penyimpanan arsip.</li>
                            <li>Melaksanakan uji tuntas atau kegiatan penyaringan lainnya (termasuk, dengan tidak terbatas pada, pemeriksaan latar belakang) sesuai dengan kewajiban hukum atau peraturan atau prosedur manajemen risiko kami yang mungkin diwajibkan oleh hukum atau yang telah diberlakukan oleh kami.</li>
                            <li>Mengaudit layanan kami atau bisnis jastipinAja!.</li>
                            <li>Mencegah atau menyelidiki pelanggaran nyata atau dugaan pelanggaran dari Syarat & Ketentuan setiap penipuan, kegiatan yang melanggar hukum, pembiaran atau kesalahan, baik yang berhubungan dengan penggunaan layanan kami oleh anda atau setiap hal lain yang timbul dari hubungan anda dengan kami.</li>
                            <li>Menyimpan, menyelenggarakan, membuat cadangan (baik untuk pemulihan setelah bencana atau hal lainnya) data pribadi anda, baik di dalam atau diluar yurisdiksi anda.</li>
                            <li>Berurusan dengan dan/atau memfasilitasi transaksi aset bisnis atau kemungkinan transaksi aset bisnis, di mana transaksi tersebut melibatkan JastipinAja! sebagai peserta atau hanya melibatkan perusahaan terkait atau afiliasi JastipinAja! sebagai peserta atau melibatkan JastipinAja! dan/atau satu perusahaan terkait atau afiliasi JastipinAja! sebagai peserta, dan mungkin juga ada organisasi pihak ketiga lainnya yang menjadi peserta dalam transaksi tersebut. “Transaksi aset bisnis” mengacu pada pembelian, penjualan, penyewaan, penggabungan, peleburan atau bentuk akuisisi, pelepasan, atau pembiayaan suatu organisasi atau bagian dari suatu organisasi atau bisnis maupun asset apapun dari suatu organisasi; dan/atau</li>
                            <li>Setiap tujuan lain yang akan kami beritahukan kepada anda pada saat memperoleh persetujuan anda.</li>
                        </ul>
                        <p><span>2. Karena tujuan kami akan/mungkin mengumpulkan, menggunakan, mengungkapkan atau mengolah data pribadi anda tergantung pada stuasi yang dihadapi, tujuan tersebut mungkin tidak tertera di atas. Akan tetapi, kami akan memberi tahu Anda tentang tujuan lain semacam itu pada saat memperoleh persetujuan anda, kecuali pengolahan data yang berlaku tanpa persetujuan anda diizinkan oleh Undang-Undang Privasi.</span></p>
                        <hr/>
                        <p><span><strong>G.&nbsp;&nbsp;Bagaimana Kami Melindungi dan Menarik Informasi Pelanggan?</strong></span></p>
                        <ul>
                            <li>Kami menerapkan berbagai langkah pengamanan dan berusaha untuk memastikan keamanan data pribadi anda di sistem kami. Data pribadi pengguna berada di belakang jaringan yang aman dan hanya dapat diakses oleh sejumlah kecil karyawan yang memiliki hak khusus ke sistem tersebut. Namun demikian, tidak adanya jaminan atau keamanan absolut tidak dapat dihindarkan.</li>
                            <li>Kami akan menyimpan data pribadi sesuai dengan Undang-Undang Privasi dan/atau hukum lain yang berlaku. Yaitu, kami akan memusnahkan atau menganonimkan data pribadi anda ketika kami secara wajar menganggap bahwa (i) tujuan data pribadi yang dikumpulkan itu tidak lagi difungsikan oleh penyimpanan data pribadi tersebut; (ii) Penyimpanan tidak lagi diperlukan untuk tujuan hukum atau bisnis apa pun ; (iii) Tidak ada surat perintah yang melegitimasi untuk melakukan penarikan data pribadi tersebut lebih jauh. Jika anda berhenti menggunakan aplikasi kami dan/atau layanan diakhiri atau ditarik kembali, kami dapat terus menyimpan, menggunakan, dan/atau mengungkapkan data pribadi anda sesuai dengan Kebijakan Privasi dan kewajiban kami berdasarkan Undang-Undang Privasi. Tunduk terhadap hukum yang berlaku, kami dapat secara aman membuang data pribadi anda tanpa pemberitahuan sebelumnya kepada anda.</li>
                        </ul>
                        <hr/>
                        <p><span><strong>H.&nbsp;&nbsp;Bagaimana Kami Melindungi dan Menarik Informasi Pelanggan?</strong></span></p>
                        <p><span>1. Dalam menjalankan bisnis, kami akan/perlu mengungkapkan data pribadi anda kepada penyedia layanan pihak ketiga, agen dan/atau afiliasi atau perusahaan terkait kami, dan/atau pihak ketiga lainnya, untuk satu atau lebih tujuan yang disebutkan di Poin F. Penyedia layanan pihak ketiga, agen dan/atau afiliasi atau perusahaan terkait dan/atau pihak ketiga lainnya tersebut akan mengolah data pribadi anda atas nama kami atau pihak lainnya, untuk satu atau lebih tujuan yang disebutkan di Poin F. Pihak ketiga tersebut termasuk, dengan tidak terbatas pada :</span></p>
                        <ul>
                            <li>Anak perusahaan, afiliasi dan perusahaan terkait kami.</li>
                            <li>Pengguna lainnya dari Aplikasi untuk satu atau lebih tujuan di Poin F.</li>
                            <li>Kontraktor, agen, penyedia layanan dan pihak ketiga lainnya yang kami gunakan untuk mendukung bisnis kami. Ini termasuk namun tidak terbatas pada mereka yang menyediakan layanan administratif atau lainnya kepada kami seperti, jasa pos, perusahaan telekomunikasi, perusahaan teknologi informasi dan pusat data.</li>
                            <li>Pembeli atau penerus lainnya dalam hal terjadi penggabungan, divestasi, restrukturisasi, reorganisasi, pembubaran atau penjualan atau pengalihan lainnya atas beberapa atau semua aset JastipinAja!, baik secara berkelanjutan atau sebagai bagian dari kepailitan, likuidasi atau proses serupa, dimana data pribadi yang dimiliki oleh JastipinAja! tentang pengguna aplikasi kami adalah salah satu asset yang dialihkan; atau kepada rekanan dalam suatu transaksi aset bisnis yang melibatkan JastipinAja! atau salah satu afiliasi atau perusahaan terkaitnya; dan</li>
                            <li>Pihak ketiga kepada siapa kami mengungkapkan data tersebut untuk satu tujuan atau lebih dan pihak ketiga tersebut pada gilirannya akan mengumpulkan dan mengolah data pribadi anda untuk satu tujuan atau lebih.</li>
                        </ul>
                        <p><span>2. Ini mungkin memerlukan, antara lain, berbagai informasi statistik dan demografis tentang pengguna kami dan penggunaan layanan oleh mereka kepada pemasok iklan dan pemrograman. Ini tidak akan termasuk hal apapun yang dapat digunakan untuk mengidentifikasi anda secara khusus atau menemukan informasi pribadi tentang diri anda.</span></p>
                        <p><span>3. Untuk menghindari keraguan, dalam hal Undang-Undang Privasi atau hukum yang berlaku lainnya mengizinkan suatu organisasi seperti kami untuk mengumpulkan, menggunakan atau mengungkapkan data pribadi anda tanpa persetujuan anda, izin yang diberikan oleh hukum tersebut akan terus berlaku.</span></p>
                        <p><span>4. Pihak ketiga mungkin menyadap atau mengakses data pribadi yang dikirimkan ke atau tersimpan di aplikasi tanpa izin, teknologi mungkin mengalami kerusakan fungsi atau tidak bekerja seperti yang diharapkan, atau seseorang mungkin mengakses, memanfaatkan atau menyalahgunakan informasi tanpa ada kesalahan dari pihak kami. Meski demikian kami akan menggunakan peraturan keamanan yang wajar untuk melindungi data pribadi anda seperti yang diisyaratkan oleh Undang-Undang Privasi; akan tetapi tidak dapat dihindari, tidak ada jaminan keamanan mutlak seperti tetapi tidak terbatas pada pengungkapan tanpa izin yang timbul dari peretasan yang berbahaya dan canggih oleh pihak yang tidak senang atau memusuhi tanpa adanya kesalahan dari pihak kami.</span></p>
                        <hr/>
                        <p><span><strong>I.&nbsp;&nbsp;Informasi Tentang Anak-Anak</strong></span></p>
                        <p><span>Aplikasi JastipinAja! tidak ditujukan untuk anak-anak di bawah usia 13 tahun. Kami tidak secara sengaja mengumpulkan atau menyimpan data pribadi atau informasi non-pribadi apapun dari siapa pun di bawah usia 13 tahun dan bagian apapun dari Aplikasi JastipinAja! tidak ditujukan untuk anak-anak di bawah usia 13 tahun. Sebagai orang tua atau wali hukum yang sah, mohon untuk tidak memberikan ijin bagi anak-anak yang berada di asuhan anda untuk menyerahkan data pribadi ke JastipinAja!. Dalam hal data pribadi dari anak-anak di bawah usia 13 tahun yang berada di bawah asuhan anda dibuka kepada JastipinAja!, anda dengan ini menyetujui pemrosesan data pribadi anak tersebut dan menerima serta menyetujui untuk terikat pada Kebijakan Privasi ini atas nama anak tersebut. Kami akan menutup setiap akun yang digunakan secara ekslusif oleh anak-anak tersebut dan akan mengeluarkan dan/atau menghapus setiap data pribadi yang kami yakini dikirimkan tanpa persetujuan orang tua atau wali hukum yang sah oleh anak di bawah usia 13 tahun.</span></p>
                        <hr/>
                        <p><span><strong>J.&nbsp;&nbsp;Informasi Yang Dikumpulkan Oleh Pihak Ketiga</strong></span></p>
                        <p><span>Kami dan pihak ketiga, dapat sewaktu-waktu menyediakan unduhan aplikasi perangkat lunak untuk penggunaan anda pada aplikasi. Semua aplikasi ini dapat secara terpisah mengakses, dan mengizinkan pihak ketiga untuk melihat, informasi yang dapat mengenali anda, seperti nama anda, ID Pengguna, Alamat IP perangkat anda atau informasi lainnya, seperti cookie apa yang mungkin sudah diinstal sebelumnya, atau yang diinstal untuk anda oleh aplikasi perangkat lunak pihak ketiga atau situs web. Selain itu semua aplikasi ini mungkin meminta anda untuk memberikan informasi tambahan secara langsung kepada pihak ketiga. Produk atau layanan pihak ketiga melalui aplikasi-aplikasi ini tidak dimiliki atau dikendalikan oleh JastipinAja! Anda didorong untuk membaca persyaratan dan kebijakan lainnya yang diterbitkan oleh pihak ketiga tersebut pada situs web mereka atau lainnya.</span></p>
                        <hr/>
                        <p><span><strong>K.&nbsp;&nbsp;Penyangkalan Mengenai Keamanan dan Situs Pihak Ketiga</strong></span></p>
                        <p><span>1. Kami tidak menjamin keamanan data pribadi dan/atau informasi lainnya yang anda berikan pada situs pihak ketiga. Kami memang mengimplementasikan variasi tindakan keamanan untuk menjaga keselamatan data pribadi anda yang ada di kami atau di bawah kendali kami. Data pribadi anda ditampung di balik jaringan aman dan hanya dapat diakses oleh sejumlah orang terbatas yang memiliki hak akses khusus ke sistem tersebut, dan diwajibkan untuk menjaga kerahasiaan data pribadi tersebut. Apabila anda melakukan pemesanan atau mengakses data pribadi, kami menawarkan penggunaan server yang aman. Semua data pribadi atau informasi sensitif yang anda berikan, dienkripsi ke dalam database kami dan hanya bisa diakses sebagaimana yang tertera di atas.</span></p>
                        <p><span>2. Dalam upaya menyediakan anda dengan nilai yang meningkat, kami dapat memilih berbagai situs web pihak ketiga untuk ditautkan, dan membingkai di dalam aplikasi kami. Kami juga dapat berpartisipasi dalam pemberian merek bersama dan hubungan lainnya untuk menawarkan e-commerce dan layanan serta fitur lain bagi pengunjung kami. Semua situs yang tertaut ini memiliki kebijakan privasi tersendiri dan independen serta pengaturan keamanan. Bahkan, jika pihak ketiga terafiliasi dengan kami, kami tidak memiliki kendali atas situs-situs yang tertaut ini, masing-masing memiliki privasi dan praktik pengumpulan data tersendiri yang terpisah dari kami. Data yang dikumpulkan oleh mitra merk-bersama kami atau situs web pihak ketiga (bahkan, jika ditawarkan pada atau melalui aplikasi kami) mungkin tidak diterima oleh kami.</span></p>
                        <p><span>3. Oleh karena itu kami tidak bertanggung jawab maupun mempertanggungjawabkan konten, pengaturan keamanan (atau tidak adanya pengaturan keamanan), dan aktivitas situs-situs terkait ini. Situs-situs yang terkait ini hanya untuk kenyamanan anda, dan oleh karenanya anda mengaksesnya atas resiko anda sendiri. Namun begitu, kami berupaya melindungi integritas aplikasi kami dan tautan yang ditempatkan pada masing-masing situs, dan oleh karena itu, kami menyambut setiap umpan-balik mengenai situs-situs yang tertaut ini (termasuk, namun tidak terbatas, jika tautan tertentu tidak berfungsi).</span></p>
                        <hr/>
                        <p><span><strong>L.&nbsp;&nbsp;Bagaimana Anda Dapat Mencabut Persetujuan, Meminta Akses Ke, Atau Mengkoreksi Informasi Yang Sudah Anda Berikan Kepada Kami?</strong></span></p>
                        <p><span>1. Mencabut Persetujuan</span></p>
                        <p>Anda dapat mencabut persetujuan anda untuk pengumpulan, penggunaan dan/atau pengungkapan data pribadi anda yang kami miliki, atau berada di bawah kendali kami, dengan mengirim email ke alamat : JastipinAja@aldeoz.com, dan kami akan memproses permintaan anda sesuai dengan Kebijakan Privasi ini dan kewajiban-kewajiban kami berdasarkan Undang-Undang Privasi dan hukum yang berlaku lainnya. Bagaimanapun, pencabutan persetujuan anda dapat berarti bahwa kami tidak akan dapat melanjutkan menyediakan layanan bagi anda, dan kami mungkin harus mengakhiri hubungan dengan anda dan/atau kontrak yang anda buat dengan kami.</p>
                        <p>2. Meminta akses untuk, atau Pembetulan Data Pribadi</p>
                        <ul>
                            <li>Apabila anda memiliki akun dengan kami, anda dapat mengakses dan/atau membetulkan sendiri beberapa data pribadi anda yang saat ini kami miliki atau kendalikan melalui halaman pengaturan akun di aplikasi. Namun untuk pembetulan beberapa data pribadi mengharuskan anda untuk mengubahnya dengan cara mengirim email ke alamat : JastipinAja@aldeoz.com. Kami akan membutuhkan cukup informasi dari anda untuk memastikan identitas anda serta sifat permintaan anda agar kami dapat menangani permintaan anda.</li>
                            <li>Kami dapat juga membebankan biaya yang wajar kepada anda untuk menangani dan memproses permintaan anda untuk mengakses data pribadi anda. Jika kami memilih untuk membebankan biaya, kami akan memberi anda perkiraan biaya yang akan dibebankan secara tertulis. Harap diperhatikan, bahwa kami tidak wajib menanggapi atau mengurus permintaan akses anda, kecuali anda sudah setuju untuk membayar biayanya.</li>
                            <li>Kami berhak menolak untuk mengkoreksi data pribadi anda sesuai dengan ketetapan sebagaimana diuraikan dalam undang-Undang Privasi, dan bilamana diwajibkan dan/atau memberikan hak kepada organisasi untuk menolak mengkoreksi data pribadi ke dalam keadaan yang dinyatakan.</li>
                        </ul>
                        <hr/>
                        <p><span><strong>M.&nbsp;&nbsp;Pertanyaan, Masalah atau Keluhan? Hubungi Kami</strong></span></p>
                        <p>Apabila anda memiliki pertanyaan atau masalah tentang praktik privasi kami mohon hubungi kami melalui e-mail di JastipinAja@aldeoz.com.</p>
                    </div>
                </div>
            </div>
        )
    }
}